updated help text

diff --git a/jpw b/jpw
--- a/jpw
+++ b/jpw
@@ -2,7 +2,7 @@
 
 NAME="jpw"
 VERSION="2025.03.25"
-DESCRIPTION="a simple build-from-source package manager for GNU/Linux"
+DESCRIPTION="a simplicty-focused package manager for GNU/Linux"
 
 error() {
 	printf "error: %s\n" "$1"
@@ -20,19 +20,21 @@ require_root() {
 }
 
 usage() {
-	printf "%s %s, %s\n" "$NAME" "$VERSION" "$DESCRIPTION"
+	printf "%s %s\n%s\n\n" "$NAME" "$VERSION" "$DESCRIPTION"
+
 	printf "usage: %s <command>\n" "$0"
 
-	declare -A COMMANDS=(
-		["help"]="print this help text and exit"
-		["install"]="install a package"
-		["uninstall"]="uninstall a package"
-		["installed"]="list installed packages"
-	)
+	printf "\ncommands:\n"
+	printf "  %-25s %s\n" "get [pkg [-cfg=*]...]"		"retrieve and install package(s)"
+	printf "  %-25s %s\n" "rid [pkg...]" 						"remove package(s) and associated files"
+	printf "  %-25s %s\n" "via" 										"list packages installed via this utility"
+	printf "  %-25s %s\n" "help" 										"print this help text and exit"
+	printf "  %-25s %s\n" "about" 									"print the version, license stub, and warranty stub"
 
-	for COMMAND in "${!COMMANDS[@]}"; do
-		printf "  %-20s %s\n" "$COMMAND" "${COMMANDS[$COMMAND]}"
-	done
+	printf "\npackage format:\n"
+	printf "  <name>[:<version>]\n"
+	
+	printf "\nsubmit issue reports to <https://github.com/jonathanpwalton/jpw>\n"
 
 	exit 0
 }
@@ -73,6 +75,7 @@ uninstall_package() {
 install_package() {
 	pkg=$1
 	ver=$2
+	cfg=$3
 
 	if [[ "${installed[$pkg]+1}" ]]; then
 		printf "'%s' version '%s' was previously installed, do you wish to replace it with version '%s'? " "$pkg" "${installed[$pkg]}" "$ver"
@@ -124,7 +127,7 @@ install_package() {
 				$extract $dir/$(basename "$src")
 				rm -f $dir/$(basename "$src")
 				cd $dir/$dst
-				./configure
+				./configure $cfg
 				make
 				make install
 				make clean
@@ -139,7 +142,9 @@ install_package() {
 			error "building unimplemented for $build";;
 	esac
 
-	if ! /usr/bin/env bash install; then 
+	if ! /usr/bin/env bash install; then
+		cwd "/"
+		rm -rf "$dir"
 		error "failed to install '$pkg' version '$ver'";
 	fi
 
@@ -155,39 +160,50 @@ case "$cmd" in
 		error "command not supplied, try '$0 help' for more information";;
 	help )
 		usage;;
-	install )
+	about )
+		printf "%s %s\nCopyright (C) 2025 Jonathan Walton\n\n" $NAME $VERSION
+		printf "License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>\n"
+    printf "This is free software: you are free to change and redistribute it.\n"
+		printf "There is NO WARRANTY, to the extent permitted by law.\n";;
+	get )
 		require_root
 
 		if [[ -z $1 ]]; then
-			error "no package to install, try '$0 help' for more information"
+			error "no package to get, try '$0 help' for more information"
 		fi
 
 		while (("$#")); do
 			IFS=":" read -ra pkg_ver <<< "$1"
+			shift
 
 			if [[ -z ${pkg_ver[1]} ]]; then
 				pkg_ver[1]="latest"
 			fi
 
-			install_package "${pkg_ver[0]}" "${pkg_ver[1]}"
-			shift
+			if [[ $1 = --cfg=* ]]; then
+				pre="--cfg="
+				cfg=${1#"$pre"}
+				shift
+			fi
+
+			install_package "${pkg_ver[0]}" "${pkg_ver[1]}" "$cfg"
 		done;;
-	uninstall )
+	rid )
 		require_root
 
 		if [[ -z $1 ]]; then
-			error "no package to uninstall, try '$0 help' for more information"
+			error "no package to rid, try '$0 help' for more information"
 		fi
 
 		while (("$#")); do
 			if [[ ! ${installed[$1]+1} ]]; then
-				error "cannot uninstall not-installed package '$1'"
+				error "cannot rid not-installed package '$1'"
 			fi
 
 			uninstall_package "$1"
 			shift
 		done;;
-	installed )
+	via )
 		for pkg in "${!installed[@]}"; do
 			printf "%s %s\n" "$pkg" "${installed[$pkg]}"
 		done;;
