begin migration of install to bash

diff --git a/jpw b/jpw
--- a/jpw
+++ b/jpw
@@ -1,120 +1,149 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-import os, sys, re, argparse, subprocess, shutil
-from pathlib import Path
-from urllib.parse import urlparse, ParseResult
-from urllib.request import urlopen
-from urllib.error import URLError
-from tempfile import TemporaryDirectory
-from sys import stderr, stdout
-from json import loads as parse_json
+NAME="jpw"
+VERSION="0.0.1"
+DESCRIPTION="a simple build-from-source package manager for GNU/Linux"
 
-def require_root():
-	if os.geteuid() != 0:
-		print('error: you cannot use this command without root privilege', file=stderr)
-		sys.exit(1)
+commands=(
+	["help"]="display this help text and exit"
+	["install"]="install a package"
+	["uninstall"]="uninstall a package"
+)
 
-def package_arg(value: str):
-	if not re.compile(r'[a-zA-Z0-9\-_]+(::(latest|[0-9\.]+))?').fullmatch(value):
-		raise argparse.ArgumentTypeError(f'{repr(value)} is not a valid package specifier')
-	return value
+error () {
+	echo "error: $1"
+	exit 1
+}
 
-def package_name_arg(value: str):
-	if not re.compile(r'[a-zA-Z0-9\-_]+').fullmatch(value):
-		raise argparse.ArgumentTypeError(f'{repr(value)} is not a valid package name')
-	return value
+require_root () {
+	if [ "$EUID" -ne 0 ]; then
+		error "you cannot use this command unless you are root"
+	fi
+}
 
-parser = argparse.ArgumentParser()
-parser_command = parser.add_subparsers(required=True, dest='command')
-parser_install = parser_command.add_parser('install')
-parser_install.add_argument('packages', type=package_arg, nargs='+')
-parser_uninstall = parser_command.add_parser('uninstall')
-parser_uninstall.add_argument('packages', type=package_name_arg, nargs='+')
+usage () {
+	echo "${NAME} ${VERSION}, ${DESCRIPTION}"
+	echo "usage: $0 <command>"
+	exit 0
+}
 
-args = parser.parse_args()
+declare -A installed
 
-cache_installed = Path('/var/cache/jpw/.installed')
-try: installed = {line[0]: line[1] for line in [line.split('::') for line in cache_installed.read_text().splitlines()]}
-except FileNotFoundError: installed = {}
+write_installed () {
+	require_root
+	rm -f /var/cache/jpw/.installed
+	for pkg in "${!installed[@]}"; do
+		echo "${pkg}:${installed[$pkg]}" >> /var/cache/jpw/.installed
+	done
+}
 
-if args.command == 'install':
-	require_root()
-	cache_installed.parent.mkdir(parents=True, exist_ok=True)
+if [[ -e /var/cache/jpw/.installed ]]; then
+	mapfile INSTALLED_LINES < /var/cache/jpw/.installed
 
-	for argument in args.packages:
-		argument = argument.split('::')
-		version = argument[1] if len(argument) == 2 else 'latest'
-		name = argument[0]
-		json: dict = None
+	for INSTALLED_LINE in "${INSTALLED_LINES[@]}"; do
+		IFS=':' read -ra LINE <<< "$INSTALLED_LINE"
+		installed[${LINE[0]}]=${LINE[1]}
+	done
+fi
 
-		try:
-			with TemporaryDirectory() as tmpdir:
-				if subprocess.run(['wget', '--no-cache', '-q', '--show-progress', f'https://raw.githubusercontent.com/jonathanpwalton/jpw/refs/heads/main/pkg/{name}.json'], cwd=tmpdir, stdout=stdout, stderr=stderr).returncode != 0:
-					raise URLError
-			
-				json = parse_json(Path(f'{tmpdir}/{name}.json').read_text())
-		except URLError:
-			parser.error(f'no such package {repr(name)}')
+if [ -z "$1" ]; then
+	error "command not supplied, try '$0 help' for more information"
+elif [ "$1" = "help" ]; then
+	usage
+elif [ "$1" = "install" ]; then
+	shift
+	require_root
+	
+	while (("$#")); do
+		IFS=":" read -ra pkg_ver <<< "$1"
 
-		version = json['latest'] if version == 'latest' else version
+		if [ -z "${pkg_ver[1]}" ]; then
+			pkg_ver[1]="latest"
+		fi
 
-		if version not in json['versions']:
-			parser.error(f'no such version {repr(version)} of package {repr(name)}')
+		tmpdir="$(mktemp)dir"
+		mkdir "$tmpdir"
+		cd "$tmpdir" || error "failed to cd /tmp"
 
-		if name in installed:
-			subprocess.run(['bash', f'/var/cache/jpw/{name}/uninstall'])
-			shutil.rmtree(f'/var/cache/jpw/{name}')
+		if ! wget --no-cache -q --show-progress "https://raw.githubusercontent.com/jonathanpwalton/jpw/refs/heads/main/pkg/${pkg_ver[0]}"; then
+			error "no such package '${pkg_ver[0]}'"
+		fi
 
-		Path(f'/var/cache/jpw/{name}').mkdir(parents=True, exist_ok=True)
-
-		ref = json['versions'][version]
-		src: ParseResult = urlparse(ref['src'])
-		tar: str = None
-
-		if src.path.endswith('.tar.gz'):
-			tar = f'tar xzf'
-		else:
-			raise NotImplementedError(src.path)
-
-		if ref['miu'] == 'gnu':
-			Path(f'/var/cache/jpw/{name}/install').write_text('\n'.join([
-				'set -e',
-				f'wget -q --show-progress {ref['src']}',
-				f'{tar} {Path(src.path).name}',
-				f'rm -f {Path(src.path).name}',
-				f'cd {ref['dst']}',
-				'./configure',
-				'make',
-				'make install',
-				'make clean'
-			]))
-
-			Path(f'/var/cache/jpw/{name}/uninstall').write_text('\n'.join([
-				'set -e',
-				f'cd {ref['dst']}',
-				'make uninstall'
-			]))
-		else:
-			raise NotImplementedError(ref['miu'])
+		if [ "${pkg_ver[1]}" == "latest" ]; then
+			pkg_ver[1]="$(/usr/bin/env bash "${pkg_ver[0]}" latest)"
+		fi
 		
-		if subprocess.run(['bash', f'/var/cache/jpw/{name}/install'], cwd=f'/var/cache/jpw/{name}').returncode != 0:
-			parser.error(f'failed to install {repr(name)} version {repr(version)}')
+		if [ -z "$(/usr/bin/env bash "${pkg_ver[0]}" versions "${pkg_ver[1]}" src)" ]; then
+			error "no such version '${pkg_ver[1]}' for '${pkg_ver[0]}'"
+		fi
 
-		installed[name] = version
-		cache_installed.write_text('\n'.join(f'{name}::{version}' for name, version in installed.items()))
-elif args.command == 'uninstall':
-	require_root()
+		name=$(/usr/bin/env bash "${pkg_ver[0]}" name)		
+		src=$(/usr/bin/env bash "${pkg_ver[0]}" versions "${pkg_ver[1]}" src)
+		dst=$(/usr/bin/env bash "${pkg_ver[0]}" versions "${pkg_ver[1]}" dst)
+		build=$(/usr/bin/env bash "${pkg_ver[0]}" versions "${pkg_ver[1]}" build)
+		tar=""
 
-	for name in args.packages:
-		if name not in installed:
-			parser.error(f'no such package {repr(name)} installed')
+		pkgdir="/var/cache/jpw/${name}"
+		mkdir -p "$pkgdir"
+		cd "$pkgdir" || error "failed to cd /${pkgdir}"
 
-		if subprocess.run(['bash', f'/var/cache/jpw/{name}/uninstall'], cwd=f'/var/cache/jpw/{name}').returncode != 0:
-			parser.error(f'failed to uninstall {repr(name)}')
+		if [[ $src = *.tar.gz ]]; then
+			tar="tar xzf"
+		else
+			error "${src} extraction is not implemented"
+		fi
 
-		shutil.rmtree(f'/var/cache/jpw/{name}')
+		if [[ $build = "gnu" ]]; then
+			echo "
+			set -e
+			wget -q --show-progress $src
+			$tar $(basename "$src")
+			rm -f $(basename "$src")
+			cd $dst
+			./configure
+			make
+			make install
+			make clean
+			" > install
 
-		installed.pop(name)
-		cache_installed.write_text('\n'.join(f'{name}::{version}' for name, version in installed.items()))
-else:
-	raise NotImplementedError()
+			echo "
+			set -e
+			cd $dst
+			make uninstall
+			" > uninstall
+		else
+			error "$build is not implemented"
+		fi
+
+		if ! /usr/bin/env bash install; then
+			error "failed to install ${name} version ${pkg_ver[1]}"
+		fi
+
+		installed[$name]=${pkg_ver[1]}
+		write_installed
+
+		shift
+	done
+
+else
+	error "invalid command '$1', try '$0 help' for more information"
+fi
+
+: '
+mapfile LINES < /testing
+declare -A INSTALLED
+
+for i in "${LINES[@]}"; do
+	IFS=':' read -ra LINE <<< $i
+	INSTALLED[${LINE[0]}]=${LINE[1]}
+done
+
+for i in "${!INSTALLED[@]}"; do
+  echo "key  : $i"
+  echo "value: ${INSTALLED[$i]}"
+done
+
+if [ "${INSTALLED[spell]+1}" == "1" ]; then
+	echo "hi"
+fi
+'
